### ISSUE TITLE
Problem about dq reference in  DSOGI-PLL model

### ISSUE THREAD

**Issue by ackurdeeve** [NallaLokeshReddy/Matlab-Simulink#1]
Great work! The model works fine.  I have a problem with your selection in the SRF-Pll submodule. In your model, you chose d reference (the first one) from the signal out of alpha-beta-0 to DQ function. However, I have read several papers, they all use q reference that is the same in your paper(Fig.4 General structure for DSOGI-PLL). If I change d to q, the PLL outputs exactly a 90-degree error. So I want to ask why you use d here and can get the right result. Thank you.

**Comment by NallaLokeshReddy** [comment]
Thanks for your compliment. I did not find any files related to electrical domain in your repositories. I am curious to know your area of expertise. 

Based on the considered input (abc) voltage signals and \alpha\beta transformation in the simulink file, the \alpha and beta components are obtained respectively as sin(wt) and -cos(wt) (assume the \alpha\beta components are in per-unit).  Now, the dq transformation is used such that
v_{d} = \cos(\theta)*\sin(wt) - \sin(\theta)*\cos(wt) = \sin(wt - \theta)
v_{q} = -\sin(\theta)*\sin(wt) - \cos(\theta)*\cos(wt) = -\cos(wt - \theta)

Now, if we try to make v_{d} = 0, then wt = \theta, if we try to make v_{q} = 0, then wt = \frac{\pi}{2} + \theta.

In the simulation, I tried to make v_{d} = 0. If you wish to make v_{q} to zero, then add "\frac{\pi}{2} " value to the PLL output angle to know the phase angle of the input signals.

**Comment by ackurdeeve** [comment]
Thanks for your explain. I just got a coding work using PSCAD to implement algorithms for marine wind farms connected to grid. The dynamics are of concerns of the utility. I have to build a detailed model based on the on-site power converters and their control. The PLL result is as same as that in matlab.
